version: '2'
services:
    dryhomecrm-app:
        image: dryhomecrm
        external_links:
            - dryhomecrm-mysql:mysql
            - dryhomecrm-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dryhomecrm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    dryhomecrm-mysql:
        extends:
            file: mysql.yml
            service: dryhomecrm-mysql
    dryhomecrm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dryhomecrm-elasticsearch
